#! /bin/bash

#use path according to boost installation directory in user machine
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

echo "resetting..."
if [ "$1" == "dbg" ]
then 
	gdb ../bin/comp
	exit 0
fi

INPGRAPH=$1
GRAMMAR=$2
SMT2=$3
NUMPARTITIONS=$4
MEMBUDGET=$5
NUMTHREADS=$6

rm -f $1.[dpv]*

PID=0
trap "{ kill $PID; exit 12; }" EXIT SIGINT SIGQUIT 

echo "RUN ON COMPUTER: "$(hostname) > log/cpp.$MEMBUDGET.$NUMPARTITIONS.output
echo >> log/cpp.$MEMBUDGET.$NUMPARTITIONS.output
echo "RUN ON COMPUTER: "$(hostname) > log/pmap.$MEMBUDGET.$NUMPARTITIONS.output
echo >> log/pmap.$MEMBUDGET.$NUMPARTITIONS.output

echo "running..."
# cgexec -g memory:myGroup ../bin/comp numPartitions=$NUMPARTITIONS insertionSort=false alterSchedule=false memBudget=$MEMBUDGET inputGraph=$INPGRAPH grammar=$GRAMMAR smt2File=$SMT2 numThreads=$NUMTHREADS >> log/cpp.$MEMBUDGET.$NUMPARTITIONS.output &
../bin/comp numPartitions=$NUMPARTITIONS insertionSort=false alterSchedule=false memBudget=$MEMBUDGET inputGraph=$INPGRAPH grammar=$GRAMMAR smt2File=$SMT2 numThreads=$NUMTHREADS >> log/cpp.$MEMBUDGET.$NUMPARTITIONS.output &

sleep 1
PID=$( echo $( ps -f  | grep "../bin/comp" | awk '{print $2}' ) | awk '{print $1}' )
./utilities/pmap.sh $PID >> log/pmap.$MEMBUDGET.$NUMPARTITIONS.output

